exam_score<-read.csv(file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.csv",header=FALSE)
View(exam_score)
library("dplyr")
exam_score<-rename(exam_score,id=V1,Sex=V2,math=V3,english=V4,korea=V5,class=V6)
head(exam_score)
str(exam_score)
exam_score<-read.csv(file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.csv",stringsAsFactors=FALSE,header=FALSE)
str(exam_score)
exam_score<-rename(exam_score,id=V1,Sex=V2,math=V3,english=V4,korea=V5,class=V6)
exam_score$class=as.character(exam_score$class)
str(exam_score)
#결측지 확인하기
is.na(exam_score)
table(is.na(exam_score))
table(is.na(exam_score$math))
exam_score$math=as.integer(exam_score$math)
exam_score$english=as.integer(exam_score$english)
exam_score$korea=as.integer(exam_score$korea)
mean(exam_score$math)
#결측치 제거하기
exam_score %>% filter(!is.na(math))
exam_score %>% filter(!is.na(english)&!is.na(korea))
table(is.na(exam_score))
table(is.na(exam_score$math))
exam_score %>% filter(!is.na(math))
exam_score_omit<-na.omit(exam_score)
table(is.na(exam_score_omit))
library(ggplot2)
ggplot(exam_score_omit,aes(x=Sex,y=english))+geom_boxplot()
mean(exam_score$math,na.rm=T)
exam_score$math<-ifelse(is.na(exam_score$math),64.8,exam_score$math)
mean(exam_score$math,na.rm=T)
sum(exam_score$english,na.rm=T)
sd(exam_score$korea,na.rm=T)
#class1과 class2에 따른 점수 평균 구하기
exam_score_mean<-exam_score %>% group_by(class) %>% summarise(mean_math=mean(math,na.rm=T),mean_english=mean(english,na.rm=T),mean_korea=mean(korea,na.rm=T))
exam_score_mean
#class 별 수학 점수 비교 그래프
ggplot(data=exam_score_mean,aes(x=class,y=mean_math))+geom_col()
#이상치 제거
install.packages("car")
library(car)
boxplot(Salaries$salary)$stats
ggplot(Salaries,aes(y=salary))+geom_boxplot()
ggplot(Salaries,aes(x=rank,y=salary))+geom_boxplot()
Salaries$salary<-ifelse(Salaries$salary<57800|Salaries$salary>194800,NA,Salaries$salary)
table(is.na(Salaries$salary))
Salaries_omit<-na.omit(Salaries)
table(is.na(Salaries_omit))
a<-read.table(file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.txt",sep="\t")
View(a)
install.packages("readxl")
library(readxl)
read_excel("C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.xls")
write.csv(exam_score_omit,file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score_omit.csv")

# R 빅데이터 데이터시각화
library(ggplot2)
data(mtcars)
str(mtcars)
head(mtcars)
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_point()
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_point()+labs(title="Fuel Consumption vs Weight",x="Weight",y="Fuel Consumption")
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_point()+labs(title="Fuel Consumption vs Weight",x="weight",y="Fuel Consumption")+xlim(0,7)+ylim(0,40)
mtcars$cyl=as.character(mtcars$cyl)
ggplot(data=mtcars,aes(x=cyl,y=mpg))+geom_boxplot()
ggplot(data=mtcars,aes(x=wt,y=mpg,col=cyl))+geom_point()
library(dplyr)
mtcars_cylmean <- mtcars %>% group_by(cyl) %>% summarise(mean_mpg=mean(mpg))
mtcars_cylmean
ggplot(data=mtcars_cylmean,aes(x=cyl,y=mean_mpg))+geom_col()
ggplot(data=mtcars_cylmean,aes(x=reorder(cyl,-mean_mpg),y=mean_mpg))+geom_col()
ggplot(data=mtcars,aes(x=cyl))+geom_bar()
unique(mpg$cyl)
ggplot(data=mtcars,aes(x=mpg))+geom_bar()
cyl_freq<-table(mtcars$cyl)
pie(cyl_freq)
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_smooth()
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_line()
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_smooth()+geom_point()
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_point(pch=17,color="pink",size=2)+  geom_smooth(method="lm",color="red",linetype=2,size=1)+labs(title="Fuel Cosumption vs Weight", x="Weight(1000 lbs)",y="Fuel Consump(miles/gallon)")
ggplot(data=mtcars,aes(x=wt,y=mpg))+geom_point(pch=17,color="pink",size=3)+
  geom_smooth(method="lm",color="red",linetype=2,size=1)+geom_text(label=rownames(mtcars),hjust=0,vjust=0,nudge_y=0.7,size=2)+labs(title="Fuel Comsumption vs Weight",x="Weight(1000 lbs)",y="fuel Consumption")
  
install.packages("car")
library(car)
data(Salaries)
str(Salaries)
head(Salaries)
graph1<-ggplot(Salaries,aes(x=rank))+geom_bar()
graph1
graph2=ggplot(Salaries,aes(x=salary))+geom_histogram()
graph2
Salaries<-rename(Salaries,workperiod=yrs.since.phd)
graph3<-ggplot(Salaries,aes(x=workperiod,y=salary))+geom_point()
graph3
graph4<-ggplot(Salaries,aes(x=rank,y=salary))+geom_boxplot()
install.packages("gridExtra")
library(gridExtra)
grid.arrange(graph1,graph2,graph3,graph4,nrow=2,ncol=2)
ggplot(Salaries,aes(x=salary,fill=rank))+geom_density(alpha=0.5)
ggplot(Salaries,aes(x=workperiod,y=salary,color=rank))+geom_point()
ggplot(Salaries,aes(x=workperiod,y=salary,color=rank,shape=sex))+geom_point()
ggplot(Salaries,aes(x=rank,fill=sex))+geom_bar(position="dodge")

data(economics)
str(economics)
head(economics)
ggplot(data=economics,aes(x=date,y=unemploy))+geom_line()
ggplot(data=economics,aes(x=date,y=psavert))+geom_line()

data("diamonds")
str(diamonds)
head(diamonds)
ggplot(data=diamonds,aes(group=cut_width(carat,width=0.3),x=price,y=carat))+geom_boxplot(color="blue",fill="gold")+labs(title="Diamond Price Distribution by Carat",x="Carat",y="Price(dollars)")

graph1<-ggplot(diamonds,aes(x=price,y=carat,color=color))+geom_point()
graph2<-ggplot(diamonds,aes(x=price,y=carat,color=clarity))+geom_point()
graph3<-ggplot(diamonds,aes(x=price,y=carat,color=cut))+geom_point()
grid.arrange(graph1,graph2,graph3)
ggplot(diamonds,aes(x=color,y=price))+geom_boxplot()
ggplot(diamonds,aes(x=clarity,y=price))+geom_boxplot()
ggplot(diamonds,aes(x=cut,y=price))+geom_boxplot()
#21812167 유다은 