exam_score<-read.csv(file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.csv",header=FALSE)
View(exam_score)
library("dplyr")
exam_score<-rename(exam_score,id=V1,Sex=V2,math=V3,english=V4,korea=V5,class=V6)
head(exam_score)
str(exam_score)
exam_score<-read.csv(file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.csv",stringsAsFactors=FALSE,header=FALSE)
str(exam_score)
exam_score<-rename(exam_score,id=V1,Sex=V2,math=V3,english=V4,korea=V5,class=V6)
exam_score$class=as.character(exam_score$class)
str(exam_score)
#결측지 확인하기
is.na(exam_score)
table(is.na(exam_score))
table(is.na(exam_score$math))
exam_score$math=as.integer(exam_score$math)
exam_score$english=as.integer(exam_score$english)
exam_score$korea=as.integer(exam_score$korea)
mean(exam_score$math)
#결측치 제거하기
exam_score %>% filter(!is.na(math))
exam_score %>% filter(!is.na(english)&!is.na(korea))
table(is.na(exam_score))
table(is.na(exam_score$math))
exam_score %>% filter(!is.na(math))
exam_score_omit<-na.omit(exam_score)
table(is.na(exam_score_omit))
library(ggplot2)
ggplot(exam_score_omit,aes(x=Sex,y=english))+geom_boxplot()
mean(exam_score$math,na.rm=T)
exam_score$math<-ifelse(is.na(exam_score$math),64.8,exam_score$math)
mean(exam_score$math,na.rm=T)
sum(exam_score$english,na.rm=T)
sd(exam_score$korea,na.rm=T)
#class1과 class2에 따른 점수 평균 구하기
exam_score_mean<-exam_score %>% group_by(class) %>% summarise(mean_math=mean(math,na.rm=T),mean_english=mean(english,na.rm=T),mean_korea=mean(korea,na.rm=T))
exam_score_mean
#class 별 수학 점수 비교 그래프
ggplot(data=exam_score_mean,aes(x=class,y=mean_math))+geom_col()
#이상치 제거
install.packages("car")
library(car)
boxplot(Salaries$salary)$stats
ggplot(Salaries,aes(y=salary))+geom_boxplot()
ggplot(Salaries,aes(x=rank,y=salary))+geom_boxplot()
Salaries$salary<-ifelse(Salaries$salary<57800|Salaries$salary>194800,NA,Salaries$salary)
table(is.na(Salaries$salary))
Salaries_omit<-na.omit(Salaries)
table(is.na(Salaries_omit))
a<-read.table(file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.txt",sep="\t")
View(a)
install.packages("readxl")
library(readxl)
read_excel("C:/Users/Lote/Desktop/빅데이터/5주차/exam_score.xls")
write.csv(exam_score_omit,file="C:/Users/Lote/Desktop/빅데이터/5주차/exam_score_omit.csv")
